## conf
pid_filename /var/run/squid.pid
cache deny all
via off
forwarded_for delete
http_port 0.0.0.0:3128
host_verify_strict on
#logformat squid [%tl] %6tr %>a %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt
logformat timereadable %tl %6tr %>a %Ss/%03Hs %<st %rm %ru %un %Sh/%<A %mt
#retry_on_error on
#strip_query_terms off
#uri_whitespace strip
visible_hostname localhost
#error_directory /usr/share/squid/errors/fr
#icp_port 0
#icp_access deny all
#forward_timeout 30 seconds
connect_timeout 30 seconds
#read_timeout 30 seconds
#request_timeout 30 seconds
#persistent_request_timeout 1 minute
#client_lifetime 20 hours
#cache_dir null /tmp
#logfile_daemon /usr/lib64/squid/log_db_daemon
#access_log daemon:/127.0.0.1/squid_log/access_log/squid/squid

## ACL
acl localnet src 10.0.0.0/8 # RFC1918 possible internal network
acl localnet src 172.16.0.0/12  # RFC1918 possible internal network
acl localnet src 192.168.0.0/16 # RFC1918 possible internal network
acl CONNECT method CONNECT

## RULES
#http_access allow localhost
#http_access allow localnet
#http_access allow all

######## Send Logs to stdout ########
logfile_rotate 0
#cache_log stdio:/dev/stdout
access_log stdio:/dev/stdout timereadable
#cache_store_log stdio:/dev/stdout